## This function makes a list that consists of 4 functions. Through these
## functions, the list can store the original matrix and its inverse. Also,
## the list can make cacheSolve function work.

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y){
                x <<- y
                inv <- NULL
        }
        
        get <- function() x
        setinv <- function(inverse) inv <<- inverse
        getinv <- function() inv
        list(set = set, get = get, setinv = setinv, getinv = getinv)

}


## This function first checks if the list of object 'x' generated by 
## makeCacheMatrix function above contains its inverse. If so, the function
## directly returns the value stored in the list. Otherwise, the function will
## calculate the inverse of 'x' and store it in the list so that it can be
## read next time without calculating.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getinv()
        if(is.null(inv)){
                message("getting cached data")
                return(inv)
        }
        
        data <- x$get()
        inv <- solve(data, ...)
        x$setinv(inv)
        inv
}
